* VERSION 1.0
**************************************************
* Generated by RH-CPA  *
**************************************************

* include statements for external Spice models

* Component = COMP1_part_COMP1
.include "0000_CPA_Sim_1_COMP1_part_COMP1.sp"
* Component = CSP_BGA_BGA
.include "0000_CPA_Sim_1_CSP_BGA_BGA.sp"
* Component = FCHIP_FCHIP
* Simulated Layout Model ...
.include "0000_CPA_Sim_1.sp"

**************************************************
*********** Complete Channel subckt **************
**************************************************

.include "0000_CPA_Sim_1_CSP_BGA_BGA.cpp"
.include "0000_CPA_Sim_1_FCHIP_FCHIP.cpp"


.subckt REDHAWK_PKG
+ FCHIP_VDD_15_Group_0 FCHIP_VDD_15_Group_1 FCHIP_VDD_15_Group_2
+ FCHIP_VDD_15_Group_3 FCHIP_VSS_Group_0 FCHIP_VSS_Group_1 FCHIP_VSS_Group_2
+ FCHIP_VSS_Group_3

* The following commented lines include PDN component Spice nodes
*+ Group_COMP1_part_COMP1_VDD_15_1 Group_COMP1_part_COMP1_VSS_2

* call for component = COMP1_part_COMP1
xa0000_CPA_Sim_1_COMP1_part_COMP1 
+ Group_COMP1_part_COMP1_VSS_2 Group_COMP1_part_COMP1_VDD_15_1
+ a0000_CPA_Sim_1_COMP1_part_COMP1

* call for component = CSP_BGA_BGA
xa0000_CPA_Sim_1_CSP_BGA_BGA 
+ BGA_VSS_SINK_ BGA_VDD_15_SINK_
+ a0000_CPA_Sim_1_CSP_BGA_BGA



* call for Layout Model
xa0000_CPA_Sim_1 
+ FCHIP_VDD_15_Group_0 FCHIP_VDD_15_Group_1 FCHIP_VDD_15_Group_2
+ FCHIP_VDD_15_Group_3 Group_COMP1_part_COMP1_VDD_15_1 FCHIP_VSS_Group_0
+ FCHIP_VSS_Group_1 FCHIP_VSS_Group_2 FCHIP_VSS_Group_3
+ Group_COMP1_part_COMP1_VSS_2 BGA_VDD_15_SINK_ BGA_VSS_SINK_ 
+ a0000_CPA_Sim_1 


.ends REDHAWK_PKG
